// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1TT06CrQ1Nw40ZuXRPG6sOtaq8ZfVYog',
    appId: '1:476241958122:web:ad712a82b753a77028b393',
    messagingSenderId: '476241958122',
    projectId: 'chat-app-aae75',
    authDomain: 'chat-app-aae75.firebaseapp.com',
    storageBucket: 'chat-app-aae75.appspot.com',
    measurementId: 'G-RZX23XC72K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHiW6bKA1oxQ4icLf7LGjlVfK4g_ReyzI',
    appId: '1:476241958122:android:f0ba185985a420c228b393',
    messagingSenderId: '476241958122',
    projectId: 'chat-app-aae75',
    storageBucket: 'chat-app-aae75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4MLTfTivQUER67VpQ3PhS-kejqzsCj18',
    appId: '1:476241958122:ios:9d738e0adc61d29628b393',
    messagingSenderId: '476241958122',
    projectId: 'chat-app-aae75',
    storageBucket: 'chat-app-aae75.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4MLTfTivQUER67VpQ3PhS-kejqzsCj18',
    appId: '1:476241958122:ios:52657962fa0abee628b393',
    messagingSenderId: '476241958122',
    projectId: 'chat-app-aae75',
    storageBucket: 'chat-app-aae75.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
